export const CLIENT_DOMAIN = 'CLIENT_DOMAIN';

// mongo db
export const MONGO_INITDB_ROOT_USERNAME = 'MONGO_INITDB_ROOT_USERNAME';
export const MONGO_INITDB_ROOT_PASSWORD = 'MONGO_INITDB_ROOT_PASSWORD';
export const MONGO_INITDB_DATABASE = 'MONGO_INITDB_DATABASE';
export const MONGO_SERVER_IP = 'MONGO_SERVER_IP';
export const MONGO_SERVER_PORT = 'MONGO_SERVER_PORT';

// mongo express
export const ME_CONFIG_MONGODB_ADMINUSERNAME = 'ME_CONFIG_MONGODB_ADMINUSERNAME';
export const ME_CONFIG_MONGODB_ADMINPASSWORD = 'ME_CONFIG_MONGODB_ADMINPASSWORD';
export const ME_CONFIG_BASICAUTH_USERNAME = 'ME_CONFIG_BASICAUTH_USERNAME';
export const ME_CONFIG_BASICAUTH_PASSWORD = 'ME_CONFIG_BASICAUTH_PASSWORD';

// oauth
export const OAUTH_GITHUB_CLIENT_ID = 'OAUTH_GITHUB_CLIENT_ID';
export const OAUTH_GITHUB_CLIENT_SECRET = 'OAUTH_GITHUB_CLIENT_SECRET';

// JWT
export const JWT_ACCESS_SECRET = 'JWT_ACCESS_SECRET';
