version: 0.0
os: linux
files:
    - source: /
      destination: /home/ubuntu/server
file_exists_behavior: OVERWRITE
hooks:
    AfterInstall:
        - location: scripts/server_setup.sh
          timeout: 300
          runas: root
    ApplicationStart:
        - location: scripts/start_services.sh
          timeout: 300
          runas: root
        - location: scripts/start_server.sh
          timeout: 300
          runas: root