#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

origin_url="https://github.com/skkuse/2023spring_41class_team3.git"

url="$2"

if [ "$url" != "$origin_url" ]
then
    exit 0
fi

current_branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$current_branch" == "main" -o "$current_branch" == "dev" ]
then
    echo "Do not push in dev or main branch"
    exit 1
fi

exit 0